config/routes.rb
Rails.application.routes.draw do
 
  get 'pages/index'

  devise_for :adms
  get 'welcome/index'
  root 'welcome#index'
  resources :articles do
  	resources :comments 
  end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/adm.rb
class Adm < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/article.rb
class Article < ApplicationRecord
	validates :title, presence: true, uniqueness: true
	validates :down, presence: true , length: {maximum: 200}
	validates :body, presence: true
	has_many :comments , dependent: :delete_all
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :article
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
	before_action :authenticate_adm! , only: [:create, :new, :edit, :destroy ,:update]
	before_action :set_article , except: [:index, :new, :create]
	
	def index
		@articles = Article.unscoped.order("id DESC")
	end

	def show
		@comment = Comment.new
	end

	def new 
		@article = Article.new
	end 

	def create
		@article = Article.new(article_params)
	
		if @article.save 
			redirect_to @article
		else 
			render :new
		end
	end

	def edit
		
	end

	def destroy
		
		@article.destroy
		redirect_to articles_path
	end

	def update 
		

		if @article.update(article_params )
	
			redirect_to @article
		else
			render :edit
		end
	end

	private

	def set_article
		@article = Article.find(params[:id])
	end

	def article_params
		params.require(:article).permit(:title,:down,:body)
	end

end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :set_comment, only: [:show, :edit, :update, :destroy]
  before_action :set_article
  # GET /comments
  # GET /comments.json
  def index
    @comments = Comment.all
  end

  # GET /comments/1
  # GET /comments/1.json
  def show
  end

  # GET /comments/new
  def new
    @comment = Comment.new
  end

  # GET /comments/1/edit
  def edit
  end

  # POST /comments
  # POST /comments.json
  def create
    @comment = Comment.new(comment_params)
    @comment.article = @article
    respond_to do |format|
      if @comment.save
        format.html { redirect_to @comment.article, notice: 'Comment was successfully created.' }
        format.json { render :show, status: :created, location: @comment }
      else
        format.html { render :new }
        format.json { render json: @comment.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /comments/1
  # PATCH/PUT /comments/1.json
  def update
    respond_to do |format|
      if @comment.update(comment_params)
        format.html { redirect_to @comment.article, notice: 'Comment was successfully updated.' }
        format.json { render :show, status: :ok, location: @comment }
      else
        format.html { render :edit }
        format.json { render json: @comment.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /comments/1
  # DELETE /comments/1.json
  def destroy
    @comment.destroy
    respond_to do |format|
      format.html { redirect_to @article, notice: 'Comment was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_article
    @article = Article.find(params[:article_id])
    end

    def set_comment
      @comment = Comment.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def comment_params
      params.require(:comment).permit(:name, :article_id, :body)
    end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def index
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  before_action :set_article , except: [:index, :new, :create]

  def index
  	@articles = Article.unscoped.order("id DESC").limit(10)
  	
  end

  def show
		@comment = Comment.new
		
	end


private

	def set_article
		@article = Article.find(params[:id])
	end

	def article_params
		params.require(:article).permit(:title,:down,:body)
	end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/articles/_form.html.erb
<%= form_for(@article) do |f| %>
		
		<% @article.errors.full_messages.each do |message| %>
			<div class="be-red white">
				<%= message %>
			</div>
		<%end%>
		<div class= "field">
			<%= f.text_field :title, placeholder: "Título" , class:"form-control"%>
		</div>

		<div class= "field">
			<%= f.text_area :down, placeholder: "Bajada", style: "height:100px;", class:"form-control"%>
		</div>

		<div class= "field">
			<%= f.text_area :body, placeholder: "Cuerpo", style: "height:200px;", class:"form-control"%>
		</div>
		<div>
			<%= f.submit "Guardar", class:"btn"%>
		</div>

<%end%>

app/views/articles/edit.html.erb
<div style="width:80%;margin:0 auto; ">	
	<h1>Edicion de Articulos</h1>

	<%= render "form"%>
</div>

app/views/articles/index.html.erb
<div class="row center-xs">
  <div class="col-xs-8 col-md-6">

	<%  @articles.each do |article|  %>
		<div  style="border: 1px solid black">
		<h1 class="be-red white large-padding">
		Titular: 
		<%= link_to article.title, article %></h1>
		
		<h3>
		Bajada:<%= article.down %>

		</h3>
		<h4>
		Cuerpo:	<%= article.body %>
		</h4>
		<h3>
			 Fecha de creacion: <%= article.created_at %>
		</h3>
		<h3>
				Cantidad de Comentarios: <%= article.comments.count%>
		</h3>

		<% if adm_signed_in? %>
		<%= link_to "Editar", edit_article_path(article), class:"btn" %>
		 <%= link_to "Eliminar" , article , method: :delete,class:"btn" %>
		
		<%end%>
		</div>
		


		<%end%>
	</div>
</div>

app/views/articles/new.html.erb
<div style="width:80%;margin:0 auto; ">	
	<h1>Crear Nueva Noticia</h1>
	<%= render "form"%>
</div>

app/views/articles/show.html.erb
<div class="row center-xs" style="border: 1px solid black">
  <div class="col-xs-8 col-md-6">
  	<h1 class="be-red white large-padding"><%= @article.title %></h1>
		<div class ="field">
			<h2><%= @article.down %> </h2>
		</div>
		<div class ="field">
			<%= @article.body %>
		</div>
		<div class="field">
			fecha de creacion:
			<%= @article.created_at %>
		</div>
		<div class ="field">
			<h3>Comentarios:</h3>
			<ul>
				<% @article.comments.each do |comment| %>
				<li>
					<%= comment.body %> - Escrito por: <%= comment.name %>
	
				</li>
				<%end%>
				<%= render "comments/form"%>
				<h3>
					Cantidad de comentarios: <%= @article.comments.count %>
				</h3>
			</ul>
			

		</div>
		<% if adm_signed_in? %>
			<%= link_to "Editar", edit_article_path(@article), class:"btn" %>
			<%= link_to "Eliminar" , @article , method: :delete,class:"btn" %>
		<%end%>
	</div>
</div>

app/views/comments/_form.html.erb
<%= form_for([@article,@comment]) do |form| %>
  
  <div class="field">
    <%= form.label :Nombre %>
    <%= form.text_field :name, id: :comment_name %>
  </div>

  <div class="field">
    <%= form.label :cuerpo %>
    <%= form.text_area :body, id: :comment_body %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/comments/edit.html.erb
<h1>Editing Comment</h1>

<%= render 'form', comment: @comment %>

<%= link_to 'Show', @comment %> |
<%= link_to 'Back', comments_path %>

app/views/comments/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Comments</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Article</th>
      <th>Body</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @comments.each do |comment| %>
      <tr>
        <td><%= comment.name %></td>
        <td><%= comment.article %></td>
        <td><%= comment.body %></td>
        <td><%= link_to 'Show', comment %></td>
        <td><%= link_to 'Edit', edit_comment_path(comment) %></td>
        <td><%= link_to 'Destroy', comment, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Comment', new_comment_path %>

app/views/comments/new.html.erb
<h1>New Comment</h1>

<%= render 'form', comment: @comment %>

<%= link_to 'Back', comments_path %>

app/views/comments/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @comment.name %>
</p>

<p>
  <strong>Article:</strong>
  <%= @comment.article %>
</p>

<p>
  <strong>Body:</strong>
  <%= @comment.body %>
</p>

<%= link_to 'Edit', edit_comment_path(@comment) %> |
<%= link_to 'Back', comments_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Ta1</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <header>

    	<nav class= "be-red white large-padding">
    		<ul class= "no-list row center-xs">
    			<li class= "col-md">
    				<%= link_to "Inicio", root_path %>
    			</li>
    		
    		<% if adm_signed_in? %>
    			<li class= "col-md">
    				<%= link_to "Crear Noticia", new_article_path %>
    			</li>
    			
    			<li class= "col-md">
    				<%= link_to "Administrar Todas las Noticias", articles_path %>
    			</li>
    			<li class= "col-md">
    				<%= link_to "Cerrar Sesión", destroy_adm_session_path, method: :delete%>
    			</li>
    		<% else %>
    			<li class= "col-md">
    				<%= link_to "Iniciar Sesión Administrador", new_adm_session_path %>
    			</li>
    		<% end %>
    		</ul>
    	</nav>
   		<p class="notice"><%= notice %></p>
    	<p class="alert"><%= alert %></p>
   	
    <%= yield %>
  </body>
</html>

app/views/pages/index.html.erb
<h1>Pages#index</h1>
<p>Find me in app/views/pages/index.html.erb</p>

app/views/welcome/index.html.erb
<div class="row center-xs">
  <div class="col-xs-8 col-md-6">

	<%  @articles.each do |article|  %>
		<div  style="border: 1px solid black">
			<h1 class="be-red white large-padding">
			Titular: 
			<%= link_to article.title, article %></h1>
			
			<h3>
			Bajada:<%= article.down %>

			</h3>
			<h4>
			Cuerpo:	<%= article.body.truncate(500) %>
			</h4>
			<h3>
				 Fecha de creación: <%= article.created_at %>
			</h3>
			<h3>
					Cantidad de Comentarios: <%= article.comments.count%>
			</h3>
			</div>
			<%end%>
		

		


		
	</div>
</div>
	